### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by LovellHAGSC** [DyogenIBENS/Agora#1]
Hi there, thanks for your work on Agora. 
I am trying to get it installed, but am getting the following error. Any help is appreciated.
Cheers, 
John

$ bash ./checkAgoraIntegrity.sh 
---------------------------------
creates tmp directory for testing
---------------------------------
mkdir tmp
-------------------------------
check the preprocessing scripts
-------------------------------
src/preprocessing/nhxGeneTrees2phylTreeGeneTrees.py example/data/GeneTreeForest.nhx.bz2 > tmp/geneTrees.protTree
Traceback (most recent call last):
  File "src/preprocessing/nhxGeneTrees2phylTreeGeneTrees.py", line 16, in <module>
    import utils.myFile as myFile
ImportError: No module named utils.myFile

**Comment by DyogenIBENS** [comment]
Hi,
thank you for using AGORA,

you have to initialize the path to the library LibsDyogen before running the script.

export PYTHONPATH="$PYTHONPATH:$PWD/LibsDyoGen"

Cheers,

Alexandra (for the dyogen team)

**Comment by LovellHAGSC** [comment]
Thanks! Really appreciate the quick response. I think that did the trick ... at least the program ran mostly. It produced an error though. Any thoughts about what is causing this? The directory: `tmp/diags/integr/final` doesn't contain a `anc` subdirectory. 
Cheers, 
John

```
Waiting ... 16 is now finished
ls: tmp/diags/integr/final/anc/: No such file or directory
 HOHOHO problems! 
```

**Comment by DyogenIBENS** [comment]
I will need more information to help you. 
Have you installed the various libraries specified in the INSTALL file?

Could you send the complete log file of the checkAgoraIntegrity.sh bash script?

**Comment by LovellHAGSC** [comment]
I believe I followed the full installation instructions. Here is the log file
[log.txt](https://github.com/DyogenIBENS/Agora/files/5143339/log.txt)

**Comment by alouis72** [comment]
Hi,
I'm very sorry for the late answer, you should try to update the code of Agora (we just fork new developments). It should be easier to install and use.

Don't hesitate to contact me if needed.
Alexandra
