### ISSUE TITLE
Error when running agora-plants.py

### ISSUE THREAD

**Issue by cvargas88** [DyogenIBENS/Agora#11]
Hi! Thank you for developing such an interesting tool. I am trying to reconstruct the ancestral genomes of 5 species. When using the agora-basic.py pipeline I have no issues and obtain the 4 reconstructed genomes. However, when I try running the agora-plants.py pipeline using the same dataset, out of the 42 steps 2 are finished and 1 fails. When looking at the size-0.9-1.1.log file I can see the following error: 

Traceback (most recent call last):
  File "/home/cvargas/Software/AGORA/Agora/src/ALL.filterGeneFamilies-size.py", line 95, in <module>
    mkStruct(target)
  File "/home/cvargas/Software/AGORA/Agora/src/ALL.filterGeneFamilies-size.py", line 89, in mkStruct
    notseen[newanc].remove(x)
KeyError: 8118

Do you have any suggestions? thanks a lot!

**Comment by DyogenIBENS** [comment]
Hi,
thank you for using AGORA.
I will need more informations to be able to help you. 
Do you run agora from genetrees or Orthogroups?
can you check that ancGenes ids  (first column in ancGene files) are uniq per ancestor?

thanks in advance,
Alexandra

**Comment by cvargas88** [comment]
Hi Alexandra,
Thank you very much for your prompt reply. I ran it using the orthogroups. I just checked all the ancGenes.*.list files and verified that all ids are unique both within each file and also when taking all files into consideration. Anything else I should check?

Best,
Carlos

**Comment by Ne0tea** [comment]
Hi, I come up with the same error when I run agora-plants.py. have you resolved it ?

**Comment by biogeeker** [comment]
Hi, I also come up with the same error when I run agora-generic/plants/vertebrates.py, but agora-basic.py was fine.  The error was like:
```
... ...

Loading genome of ancGenes/all/ancGenes.N15.list.bz2 ... (ancestral genes) OK
Loading genome of ancGenes/all/ancGenes.N16.list.bz2 ... (ancestral genes) OK

... ...

Loading genome of ancGenes/all/ancGenes.N49.list.bz2 ... (ancestral genes) OK
Loading genome of genes/genes.1.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.2.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.3.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.4.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.5.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.6.list.bz2 ... (Ensembl) OK
Loading genome of genes/genes.7.list.bz2 ... (Ensembl) OK

... ...

Structure creation ... OK
Processing ancGenome N15
Traceback (most recent call last):
  File "/home/ancestor_chr/Agora-master/src/ALL.filterGeneFamilies-size.py", line 95, in <module>
    mkStruct(target)
  File "/home/ancestor_chr/Agora-master/src/ALL.filterGeneFamilies-size.py", line 89, in mkStruct
    notseen[newanc].remove(x)
KeyError: 5144
```

**Comment by DyogenIBENS** [comment]
Hi biogeeker,

Unfortunately, I can't reproduce this error with my own data.
would it be possible for you to give me access to the species tree you use? and/or the file ancGenes/all/ancGenes.N15.list.bz2
you can contact me on alouis@bio.ens.psl.eu if you prefer.

I'm very sorry for this issue,
Alex

**Comment by DyogenIBENS** [comment]
Hi @biogeeker, @cvargas88 and @Ne0tea 
This king of issue can appear if you have exact same gene ids between species.
A way to prevent that is to add manually a species tag in gene ids (and in Orthogroups or genetrees) such as:
geneid_specid.

Each gene ids will then be unique.

I hope this helps.
Alex
