### ISSUE TITLE
Are there any tools to build an evolutionary tree in NHX format (from Multiple sequence alignment) ? 

### ISSUE THREAD

**Issue by kuangzhuoran** [DyogenIBENS/Agora#12]
Hi！Thank you for such a useful tool!
I've considered scripting the nwk format to NHX myself, but I'm confused by the information in the NHX format, such as what is a speciation node/how do I determine which ancestor it belongs to for an ancestor node

And as far as I know most tools only output in nwk or NEXUS format， treeIO can convert NHX format to nwk format, but not vice versa

**Comment by kuangzhuoran** [comment]
Perhaps "orthologyGroups/orthologyGroups.%s.list" would be more convenient as an input file, which can be obtained with a little processing of the Orthofiner results

**Comment by DyogenIBENS** [comment]
Hi, 
sorry for the late answer. NHX is a newick format with additional annotation on each nod and leaf. 
Some tools for computing gene trees (reconciliated or not with the species tree) can output NHX (see ProfileNJ , treerecs, Treebest).
As a reminder, AGORA run with NHX trees reconciliated with species tree.
Nevertheless, as you previously mentioned, AGORA can run with orthology groups.
I hope it will resolve your problem. Don't hesitate to ask any other question if needed.
regards,
Alexandra

**Comment by kuangzhuoran** [comment]
Thank you for your reply, it helps a lot
I have a new problem, I use orthogroup as the input file but the program runs too fast, it runs in 2-3 minutes and the software is installed without any problem (./checkAgoraIntegrity.sh). There are also no obvious errors in the log files. 

Maybe I'll have to try using "GeneTreeForest"?

My Linux: Centos 8.5

[log1.txt](https://github.com/DyogenIBENS/Agora/files/9552823/log1.txt)
[log2.txt](https://github.com/DyogenIBENS/Agora/files/9552824/log2.txt)

**Comment by DyogenIBENS** [comment]
When a look a the bottom of log2.txt... I can read:
"Status: 0 to do, 1 running, 9 done, 0 failed -- 10 total
Waiting ...
task 9 report: 6.95752 sec CPU time / 3.6729 sec elapsed = 189.429% CPU usage, 64.0195 MB RAM
task 9 is now finished (status 0)
Workflow complete
Workflow report: 145.498 sec CPU time / 89.9035 sec elapsed = 161.838% CPU usage, 1052.43 MB RAM"

So agora just run on your data...
You should have results in result_vertebrates/ancGenomes/vertebrates-workflow/

**Comment by kuangzhuoran** [comment]
Thanks a lot !
It was so fast, it was all running in 2 minutes
