### ISSUE TITLE
Too many contiguous ancestral regions (CARs)

### ISSUE THREAD

**Issue by kuangzhuoran** [DyogenIBENS/Agora#14]
Hi ! 
I got 260 CARs and I have used agora-plants.py and agora-vertebrates.py. And I used orthoGroups as input
( The genus I studied has only eight species...

Is it because the number of species is too low, and is there anything I can do to improve this result?

**Comment by DyogenIBENS** [comment]
Hello, 
it is not the number of CARs that is important but the distribution of the CARs's size. You can have 260 CARS but only 15 with size > to 20 genes and a lot of very little ones. Which can lead to what we call a Chromosomal reconstruction if descendant genomes have ~15 chromosomes.
Also, the reconstruction will depend on the number of genomes you have (descendants and outgroups), the quality of assembly for each genome, the conservation in gene organisation between these genomes, the quality of annotations for each species and the relevancy of OrthoGroups (depending of the methodology used to compute them).
It's difficult to say why you have 260 CARs and if it is a problem without knowing what species you're analyzing. Unfortunately, as I don't have any clue on the data, it's hard for me to orient you on what you should expect.
Don't hesitate if you have any other question.
regards,
Alexandra

**Comment by YingChen94** [comment]
Hello Alexandra,

You said, "Also, the reconstruction will depend on the number of genomes you have (descendants and outgroups)". What do you mean by number of outgroups? For example, for the species below, if I am interested in N2, are N0 and N1 descendants outgroups in the analyses? 

I also have many continuous CARs. All the species are at chromosome-level and annotated. I am not sure how many I should use to plot extant species karyotype. I attached the N2 karyotype plot (-minChrSize=100) here in case it helps. 

Thank you!
Ying 

<img width="752" src="https://github.com/DyogenIBENS/Agora/assets/46506947/4cd6db87-d371-49fa-ab71-89109ebe71fc">
[N2.pdf](https://github.com/DyogenIBENS/Agora/files/15450548/N2.pdf)
