### ISSUE TITLE
Lack of chromosomal information

### ISSUE THREAD

**Issue by cheng-yu-zhang** [DyogenIBENS/Agora#15]
Hi, thanks for developing such a powerful tool. But when I used it, I noticed that there are a large number of species whose assembly level is only scaffold which means the chromosome information is not sufficient enough to run Agora. So, I just wonder how to deal with those species ?
For example, the genome of _Aciculoconidium aculeatum_.
[https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_003707435.1/](https://www.ncbi.nlm.nih.gov/data-hub/genome/GCA_003707435.1/)

**Comment by DyogenIBENS** [comment]
Hello,
Thank you for using AGORA.
Unfortunetly, AGORA won't be able to infer ancestral karyotypes if the extant genomes you provide are not enough assembled. The ancestral states can be as much assembled as the entry data, even less if there is a lot of rearrangement between the genomes. Pourly assembled genomes (scaffolds or contigs) can offer local information on ancestral intergenes, so it is interesting to include them in the analysis, but won't be informative for chromosomal reconstruction.
