### ISSUE TITLE
Breakpoint regions mapping to reference chromosomes

### ISSUE THREAD

**Issue by biogeeker** [DyogenIBENS/Agora#19]
`Hello, thanks for this nice tool. Can Agora output the breakpoint regions information like the NEE paper Fig. 6a? Can you recommend related tools to output the phyloview diagram shown in Figure 6c?`

![41559_2022_1956_Fig6_HTML](https://user-images.githubusercontent.com/60848442/220861453-5a008734-baf4-4a0c-ade8-b69fad702bc6.png)

**Comment by YingChen94** [comment]
Hello, did you figure out how to plot such figure? Thank you!
