### ISSUE TITLE
Error when running agora-basic.py

### ISSUE THREAD

**Issue by ArthurSilver** [DyogenIBENS/Agora#21]
Hello,
I got an error in log file under folder **ancGenomes/basic-workflow** after running agora-basic.py
```
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A8.list.bz2 ... (Ensembl) OK
Loading genome of ancGenes/all/ancGenes.A8.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A9.list.bz2 ... (Ensembl) OK
Loading genome of ancGenes/all/ancGenes.A9.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A5.list.bz2 ... (ancestral genome: diags) OK
Loading genome of ancGenes/all/ancGenes.A5.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A4.list.bz2 ... (ancestral genome: diags) OK
Loading genome of ancGenes/all/ancGenes.A4.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A2.list.bz2 ... (ancestral genome: diags) OK
Loading genome of ancGenes/all/ancGenes.A2.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A1.list.bz2 ... (ancestral genome: diags) OK
Loading genome of ancGenes/all/ancGenes.A1.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A7.list.bz2 ... (Ensembl) OK
Loading genome of ancGenes/all/ancGenes.A7.list.bz2 ... (ancestral genes) OK
Loading genome of ancBlocks/denovo-all.scaffolds/blocks.A3.list.bz2 ... (ancestral genome: diags) OK
Loading genome of ancGenes/all/ancGenes.A3.list.bz2 ... (ancestral genes) OK
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/public/renyifan/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/public/renyifan/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/public/renyifan/biosoft/Agora-master/src/convert.ancGenomes.blocks-to-genes.py", line 69, in do
    print(utils.myFile.myTSV.printLine([names[s], gene.beginning, gene.end, gene.strand, " ".join(ancGenes[gene.names[0]].names)]), file=ancGenomeFile)
TypeError: list indices must be integers or slices, not str
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/public/renyifan/biosoft/Agora-master/src/convert.ancGenomes.blocks-to-genes.py", line 74, in <module>
    multiprocessing.Pool(n_cpu).map(do, sorted(targets))
  File "/public/renyifan/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/public/renyifan/miniconda3/envs/agora/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: list indices must be integers or slices, not str
```
And I find the results of A1 to A6 are successfully output under ancGenomes, but the output files of A7 to A9 are empty. I think the reason for this cannot be the mismatch of gene names between gene list and orthogroups list , because the successful output of A6, so I wonder where the problem is.

Here's my phylogeny tree:
![QQ截图20230324091009](https://user-images.githubusercontent.com/43472588/227399558-b36227db-e36d-489f-b0f3-ad3b91f5fa59.png)

Thanks for your reply!

**Comment by DyogenIBENS** [comment]
Hi,
thanks for using AGORA.

Can you tell me if the denovo-all.scaffolds/blocks.A7.list.bz2 looks like the one for ancestral genomes that are reconstructed?

should look like:

```
A7 	 20 	 2280 10075 7872 9606 7863 7825 6462 14726 14707 10178 2302 740 15219 6715 8502 2335 4009 15733 14232 8632 	 1 1 -1 1 1 1 1 -1 -1 1 -1 -1 1 1 -1 1 -1 -1 -1 -1 	 2 1 3 1 1 2 1 16 1 5 1 1 6 2 3 1 1 2 1
A7 	 47 	 11221 5990 10654 10292 6611 7748 6203 16576 2607 11505 15665 11100 16292 14458 16509 11998 3962 4665 6234 15582 13478 12695 15474 387 12324 9728 15351 6543 12219 10467 3717 13002 3389 5658 4033 16701 7563 7517 4391 6339 526 6648 8868 8715 15292 17228 4744 	-1 1 1 1 1 1 1 -1 -1 -1 -1 1 1 1 1 1 -1 -1 1 1 -1 1 -1 1 1 -1 -1 -1 1 1 1 -1 1 -1 1 1 -1 1 -1 -1 -1 1 -1 -1 1 -1 -1 	 2 1 3 8 5 8 2 5 2 8 8 4 1 5 4 4 8 5 5 5 1 1 4 2 5 5 8 2 1 1 1 8 2 8 5 5 2 2 16 2 2 2 2 2 1 1
```

the format is (one line for ancestral bloc):
`genomeX 	 nbAncGenesInBlock 	 list_of_ancGenes_index_in_Bloc 	 list_of_ancgenes_orientations 	 list_of_supports_of_intergenes
`
thanks in advance,
Alex

**Comment by ArthurSilver** [comment]
denovo-all.scaffolds/blocks.A7.list.bz2 looks like
```
A7	1	0	1	(1)
A7	1	1	1	(1)
A7	1	2	1	(1)
A7	1	3	1	(1)
```
while blocks.A6.list.bz2 looks like 
```
A6	12	14782 3427 4795 14781 14778 14777 14776 4794 7424 14774 14771 7423	-1 1 -1 1 -1 1 -1 1 -1 1 -1 1	7 68 7 18 5 1 5 2 1 8 1
A6	9	8504 8505 8506 8507 8508 8509 8510 2236 2235	1 1 1 1 1 1 1 -1 1	9 10 5 68 10 11 6 8
A6	6	14525 14526 14527 7350 14528 14529	-1 1 -1 -1 1 -1	7 4 58 7 6
A6	6	9537 9536 5710 9535 2935 9532	-1 1 1 -1 -1 1	5 38 4 16 4
```

**Comment by ArthurSilver** [comment]
> Hi, thanks for using AGORA.
> 
> Can you tell me if the denovo-all.scaffolds/blocks.A7.list.bz2 looks like the one for ancestral genomes that are reconstructed?
> 
> should look like:
> 
> ```
> A7 	 20 	 2280 10075 7872 9606 7863 7825 6462 14726 14707 10178 2302 740 15219 6715 8502 2335 4009 15733 14232 8632 	 1 1 -1 1 1 1 1 -1 -1 1 -1 -1 1 1 -1 1 -1 -1 -1 -1 	 2 1 3 1 1 2 1 16 1 5 1 1 6 2 3 1 1 2 1
> A7 	 47 	 11221 5990 10654 10292 6611 7748 6203 16576 2607 11505 15665 11100 16292 14458 16509 11998 3962 4665 6234 15582 13478 12695 15474 387 12324 9728 15351 6543 12219 10467 3717 13002 3389 5658 4033 16701 7563 7517 4391 6339 526 6648 8868 8715 15292 17228 4744 	-1 1 1 1 1 1 1 -1 -1 -1 -1 1 1 1 1 1 -1 -1 1 1 -1 1 -1 1 1 -1 -1 -1 1 1 1 -1 1 -1 1 1 -1 1 -1 -1 -1 1 -1 -1 1 -1 -1 	 2 1 3 8 5 8 2 5 2 8 8 4 1 5 4 4 8 5 5 5 1 1 4 2 5 5 8 2 1 1 1 8 2 8 5 5 2 2 16 2 2 2 2 2 1 1
> ```
> 
> the format is (one line for ancestral bloc): `genomeX nbAncGenesInBlock list_of_ancGenes_index_in_Bloc list_of_ancgenes_orientations list_of_supports_of_intergenes ` thanks in advance, Alex

denovo-all.scaffolds/blocks.A7.list.bz2 looks like
```
A7	1	0	1	(1)
A7	1	1	1	(1)
A7	1	2	1	(1)
A7	1	3	1	(1)
```
while blocks.A6.list.bz2 looks like 
```
A6	12	14782 3427 4795 14781 14778 14777 14776 4794 7424 14774 14771 7423	-1 1 -1 1 -1 1 -1 1 -1 1 -1 1	7 68 7 18 5 1 5 2 1 8 1
A6	9	8504 8505 8506 8507 8508 8509 8510 2236 2235	1 1 1 1 1 1 1 -1 1	9 10 5 68 10 11 6 8
A6	6	14525 14526 14527 7350 14528 14529	-1 1 -1 -1 1 -1	7 4 58 7 6
A6	6	9537 9536 5710 9535 2935 9532	-1 1 1 -1 -1 1	5 38 4 16 4
```

**Comment by alouis72** [comment]
@ArthurSilver ,
Could you check if all the lines finish by (1) in denovo-all.scaffolds/ancBlocks.A7, A8, A9 ???
This kind of lines represents singletons. If you only have lines like this, it means that there is no blocks in theses ancestors (but should not be a problem for the last convertion script).

could you also give me the firsts lines of denovo-all/blocks.A7. ??

thanks in advance,
Alex

**Comment by ArthurSilver** [comment]
> @ArthurSilver , Could you check if all the lines finish by (1) in denovo-all.scaffolds/ancBlocks.A7, A8, A9 ??? This kind of lines represents singletons. If you only have lines like this, it means that there is no blocks in theses ancestors (but should not be a problem for the last convertion script).
> 
> could you also give me the firsts lines of denovo-all/blocks.A7. ??
> 
> thanks in advance, Alex

Hello Alex,

Lines in denovo-all.scaffolds/ancBlocks.A7, A8, A9 are really like this
```
A7	1	0	1	
A7	1	1	1	
A7	1	2	1	
A7	1	3	1	
A7	1	4	1
```
```
A8	1	0	1	
A8	1	1	1	
A8	1	2	1	
A8	1	3	1	
A8	1	4	1
```	
But species under A7 node are genetically close so it couldn't be no blocks in theses ancestors. How can I identify the real problems?

Thanks for your reply!

**Comment by alouis72** [comment]
Well, if the species are very close genetically, it may be a problem in the input data.

You can check two things:

- if the algorithm found conserved gene intervals for the A7,A8,A9 ancestors - that means that the files 
pairwise/pairs-all/A7.list.bz2
pairwise/pairs-all/A8.list.bz2
pairwise/pairs-all/A9.list.bz2
should contained something like that:
1152    -1      2063    -1      8
6464    1       12669   1       4
1770    1       6409    1       8
format is:
ancGene1_index orientation ancGene2_index orientation weight
the "weight" is  the nb of time this interval is seen in the comparison of extant genomes.

- If the pairwise files are not like that (you should compare to A6), that probably means that the gene names are not coherent between genome files and either the gene trees or orthogroups you provide to the pipeline (I don't know what approach you choosed to use).

I hope this helps,

Alex
