### ISSUE TITLE
Agora in living sps

### ISSUE THREAD

**Issue by DiegoSafian** [DyogenIBENS/Agora#22]
Hi,

Thanks for this fantastic repo and tools. I am just wondering if Agora can be used with genomes of closely related living sps to reconstruct the genome of their last common ancestors.  I do not see why not, but I prefer to ask.

Thanks
Diego

**Comment by alouis72** [comment]
Hello Diego,
I cannot see any problem in using AGORA on genomes of closely related living species . 
Be aware however that AGORA only reconstructs the order of the ancestral genes and not the ancestral sequences. It is therefore only useful if there are karyotipic differences between your genomes (breakpoints, translation,...). The quality of the reconstruction is also dependent on the number of genomes, the quality of the genomes assembly and annotation, as well as on the quality of the gene trees or families of homologs you will give to the pipeline. 

Alex
