### ISSUE TITLE
AssertionError in ALL.reformatGeneFamilies.py

### ISSUE THREAD

**Issue by hyBio** [DyogenIBENS/Agora#30]
```
------------------------------------------------------------------------------------------------------------------------------
| Key               | Values                                                                                                 |
------------------------------------------------------------------------------------------------------------------------------
| speciesTree       | ~/agora/Agora_data/SpeciesTree_rooted_node_labels.txt  |
| orthologyGroups   | ~/agora/Agora_data/orthoGroups/orthologyGroups.%s.list |
| IN.genesFiles     | ~/agora/Agora_data/genelists/genes.%s.list             |
| OUT.ancGenesFiles | ancGenes/all/ancGenes.%s.list.bz2                                                                      |
| OUT.genesFiles    | genes/genes.%s.list.bz2                                                                                |
------------------------------------------------------------------------------------------------------------------------------
Renaming the genes of fAcaLat ... Traceback (most recent call last):
  File "~/software/Agora/src/ALL.reformatGeneFamilies.py", line 62, in <module>
    assert oldName not in seen
AssertionError
```

First of all, thanks to the author for writing such a great program! I'm not sure why I'm getting this error, but by commenting out line 62, my program can be executed. I don't understand why the author defines an empty set of seen in line 46, but then wants to determine if column 5 of genesFiles, which is the gene identifier oldName, belongs to an empty set of seen in line 62. I don't know if there's any special intent on the author's part, and does commenting out this line have any effect on the subsequent running of the program?

https://github.com/DyogenIBENS/Agora/blob/9d1f74f83f07740dd678797f2136665f5dd49d84/src/ALL.reformatGeneFamilies.py#L62C9-L62C15

**Comment by YingChen94** [comment]
I got the same error as well. Have you figured this out yet?

**Comment by hyBio** [comment]
> I got the same error as well. Have you figured this out yet?

Yes, it works for me! It doesn’t seem to affect the results, so maybe my actions didn’t change the definitions of certain variables.

**Comment by YingChen94** [comment]
Great to know! Thank you!!

**Comment by hyBio** [comment]
> Great to know! Thank you!!

😄
