### ISSUE TITLE
drawKaryotype trouble

### ISSUE THREAD

**Issue by Alchimic007** [DyogenIBENS/Agora#31]
Hello,
Firstly, thank you for such great software as AGORA. I am really sorry to disturb you, but I have met issues in reconstructed blocks visualization with  misc.compareGenomes in recent tests. I have tried to visualize ancestor on human chromosomes without filtering by  min size of the block (-minChrSize) and  got karyograms where some block were painted black. I just want to know what black color means because in visualization of reference chromosomes there was no black color. I will attach my results to this message. Please inform me if you need any more info Thank you.

Kind regards,
Maksym 

[AGORA_last_res1.zip](https://github.com/DyogenIBENS/Agora/files/15166819/AGORA_last_res1.zip)
[AGORA_last_res2.zip](https://github.com/DyogenIBENS/Agora/files/15167010/AGORA_last_res2.zip)

**Comment by alouis72** [comment]
Hi Maksym,
thank you very much for your nice feedback on AGORA.
About the karyotype visualization, as I understand, you try to plot the human chromosomes according to the color of ancestral genes in N2 CARs.
As I can see, if you do not limit the ancestral CARs represented in Human (eventualy by minimum size), you should have 453 colors... In fact, if I remember, misc.compareGenome can draw less than ~40 colors. 
I think the white and black cells represent ancestral genes from small CARs.

(From the example in the code... Here is the plot of the A0 reference genome when minChrSize=20... As you can see, you have colored CARS, then White CARS, and Black CARs).
[A0.pdf](https://github.com/DyogenIBENS/Agora/files/15221597/A0.pdf)

I guess it should be the same for N2.
Cheers,
Alex

**Comment by YingChen94** [comment]
Hello Alex, 

Is there a way to manually select the color? For example, Fig. 1b primates in the paper has mostly grey but some segments in purple. 

Thanks!
Ying

<img width="341" src="https://github.com/DyogenIBENS/Agora/assets/46506947/bb1c2e46-4c25-4a8c-86fb-29739191e405">
