### ISSUE TITLE
Purpose of ENSEMBL.buildProteinTrees

### ISSUE THREAD

**Issue by Alchimic007** [DyogenIBENS/Agora#32]
Hi Alex,

Sorry to disturb you again.
Just wondering, is it possible to create annotated gene trees in nhx format suitable for AGORA input from  Orthofinder produced gene trees with ENSEMBL.buildProteinTrees.py. I have tried to run it with test files, as well with my own.I got this error message in  both cases: :mprylutskyi]$ python /users/hpctestuser/mprylutskyi/AGORA/Agora/src/ENSEMBL.buildProteinTrees.py /users/hpctestuser/mprylutskyi/AGORA/Agora/example/data/Species.nwk /users/hpctestuser/mprylutskyi/AGORA/Agora/example/data/GeneTreeForest.nhx.bz2 -cutoff 0.25 -scoreMethod 1
  File "/users/hpctestuser/mprylutskyi/AGORA/Agora/src/ENSEMBL.buildProteinTrees.py", line 105
    return
TabError: inconsistent use of tabs and spaces in indentation. 

I will be very appreciated for any information. Thank you.

Kind regards,

Maksym Prylutskyi

**Comment by alouis72** [comment]
Hi Maksym,
I guess you're talking about the Resolved_Gene_Trees/*.txt that are produced by Orthofinder?
Can you confirm?
If so, the ENSEMBL.buildProteinTrees.py script is not written for that. (This script is used to move duplication nodes that are not well supported in Ensembl trees).

I think I have something that could be used for that (transform nwk to nhx with species and duplication node annotations?) but I have to make some tests before.

best regards,
Alex

**Comment by Alchimic007** [comment]
Hi Alex,

Thanks for answer. Yes, I was talking about Resolved gene trees, which Orthofinder produces.
If you have something that could help with transformation of nwk to nhx with species and duplication node annotations and could share, this will be great. Thank you. 

Kind regards,

Maksym Prylutskyi

**Comment by alouis72** [comment]
Hi Maksym,
sorry for the delay.

To annotate a nwk with species and duplications, you can use a tool that has been developped by a former PostDoc in the lab:
https://github.com/delehef/chainsaw

you should be able to install it with:
`cargo install chainsaw`
if you have any problem with chainsaw, open an issue on the chainsaw repository.

To use it with OF resolved gene trees, you will have to first transform the leaf names of the trees to get the corresponding extant species tag:
I've added a script in the dev branch og AGORA repo:

src/import/orthofinder_resolved_gene_trees/addSpeciesAnnotationToOFTrees.py

And here is the procedure that was successfull for me in an Orthofinder test directory (OrthoFinder/Results_May24>):
```
mkdir AgoraData/Resolved_Gene_trees
python $AGORA/src/import/orthofinder_resolved_gene_trees/addSpeciesAnnotationToOFTrees.py -of_trees=Resolved_Gene_Trees -outdir=AgoraData/Resolved_Gene_trees/

for i in AgoraData/Resolved_Gene_trees/*; do chainsaw $i annotate --species-tree Species_Tree/SpeciesTree_rooted_node_labels.txt ; done
```

=> you should have annotated nhx trees that could be concatenated in a single forestTree files to use AGORA on it.

I hope this helps,
regards,
Alex

**Comment by Alchimic007** [comment]
Hi Alex,

Sorry for late response. Thank you for script and explanation. You saved me. Thank you again.

Kind regards,

Maksym

**Comment by alouis72** [comment]
Hi Maksym,
I'd love any feedback on the method and the Resolved_Gene_trees you use. 
The first tests I did on our data were disappointing (a lot of duplications), so if you can tell me what you feel about other data, I'd be grateful.
I don't now if it is due to the OF algorithm or our methodology to annotate the trees... :-(
best regards,
Alex
