### ISSUE TITLE
Is it possible to get ancestral nucleotide sequence?

### ISSUE THREAD

**Issue by zhyanlin** [DyogenIBENS/Agora#34]
Hello,

I found your paper when I am looking for ancestral genome sequences. Your software and database are very great! I learnt that Agora does not produce ancestral nucleotide sequence. But is there a way to get ancestral nucleotide sequence from your database?

Thank you!

**Comment by alouis72** [comment]
Hello,
We do not store any sequence in Genomicus, no ancestral nor extant ones.
You should have look at the ancestral sequence inference from the Ensembl database.(https://www.ensembl.org/info/genome/compara/ancestral_sequences.html) to get access to such data.
I hope this helps,
best regards,
Alexandra

**Comment by zhyanlin** [comment]
Thank you!
