### ISSUE TITLE
How to merge SCORPiOs

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/Agora#35]
Hello,

I see "This issue is amplified after WGD events, where all genes are duplicated at once, but can be mitigated by tree edition steps as implemented in SCORPiOs" in the article, does this mean that when the species to be analyzed is involved in a WGD (Whole Genome Duplication), it can be solved using SCORPiOs software? Could you please tell me what to do specifically?

I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Hello Jenny,
SCORPiOs (see https://github.com/DyogenIBENS/SCORPIOS) identifies gene trees where a whole-genome duplication is missing or incorrectly placed, based on the genomic locations of the duplicated genes across the different species. 
It will try to correct gene paralogies below the duplication node, based on conserved synteny between duplicated species and non duplicated outgroup species.
Depending of your data (number of WGD in the species tree, availability of non duplicated outgroup for each WGD, and of course availability of a forest of gene trees and not only hyerarchical orthologous groups), it may be interesting to run SCORPiOs on the forest before running AGORA to reconstruct ancestors.
The SCORPiOs documentation is well written and available here: 
https://scorpios.readthedocs.io/

best regards,
Alexandra

**Comment by jenny315** [comment]
Hello, thank you for your quick reply. I will try further.
Much appreciated.
Jenny
