### ISSUE TITLE
assert oldName not in seen

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/Agora#37]
Hi, Professor,
After I modified the id and reran the basic mode, I got the following error under the path "result/ancGenes". Does this mean that the gene ID still causes this problem? I used Orthofinder to generate these HOGs through [convert_hogs_sp.py]https://github.com/DyogenIBENS/Agora/issues/23#issuecomment-1518631724(https://github.com/DyogenIBENS/Agora/blob/dev/src/import/orthofinder_hogs/convert_hogs_sp.py)

```less ancGenes.log```
```

---------------------------------------------------------------------
| Key               | Values                                        |
---------------------------------------------------------------------
| speciesTree       | SpeciesTree_rerooted.txt                      |
| orthologyGroups   | orthologyGroups/orthologyGroups.%s.list       |
| IN.genesFiles     | genes/genes.%s.list                           |
| OUT.ancGenesFiles | result-basi/ancGenes/all/ancGenes.%s.list.bz2 |
| OUT.genesFiles    | result-basi/genes/genes.%s.list.bz2           |
---------------------------------------------------------------------
Renaming the genes of Aa ... 37666 OK
Renaming the genes of Bb ... 47719 OK
Renaming the genes of Cc ... 18900 OK
Renaming the genes of Dd ... 130456 OK
Renaming the genes of Ee ... 44493 OK
Renaming the genes of Ff ... 22590 OK
Renaming the genes of Gg ... 27024 OK
Renaming the genes of Hh ... 44754 OK
Renaming the genes of Ii ... Traceback (most recent call last):
  File "/data/jenny/SF/Agora/src/ALL.reformatGeneFamilies.py", line 62, in <module>
    assert oldName not in seen
AssertionError
```
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Hi Jenny,
can you check if you do not have twice the same id_gene in Ii?
This could be the pb.
If not, can you try commenting the line 62 in /data/jenny/SF/Agora/src/ALL.reformatGeneFamilies.py ?
As you can see in [issue30](https://github.com/DyogenIBENS/Agora/issues/30) it does not affect the results.

regards,
Alex

**Comment by jenny315** [comment]
Hi, Professor,
Thank you very much. I solved the problem
I appreciate your quick reply.
Jenny
