### ISSUE TITLE
Too more  CARs and how to determine the number of chromosomes

### ISSUE THREAD

**Issue by jenny315** [DyogenIBENS/Agora#38]
Hi, Professor,
I found that the ancestors of each node have more than 1,000 CARs. After further processing the results as the input file of ANGES, the result is that the ancestors of each node still have more than 300 CARs. In this case, how to determine the number of chromosomes?
I appreciate your quick reply.
Jenny

**Comment by alouis72** [comment]
Hi Jenny,
The number of Contiguous Ancestral Regions (CARs) does not necessarily reflect the quality of ancestral reconstruction. It’s possible to have a few very large CARs (approaching the gene content expected from an ancestral karyotype) and many CARs containing only two genes (which are less informative).

Two key statistics are interesting for evaluating the quality of a reconstruction: the G50 (similar to the N50 in genomic assembly, but for the number of genes, representing the size of CARs above which 50% of the ancestral genes are aggregated) and the number of CARs that aggregate X% of the ancestral genes (for example, 70%, referred to as L70 in the AGORA paper).

Algorithmic ancestral reconstruction cannot determine the exact number of ancestral chromosomes. However, it may approximate the expected number based on the available extant genome data.

Also, the quality of the reconstruction heavily depends on the quality of the input data, including:

	•	The number of extant species
	•	The quality of annotation of extant genomes
	•	The quality of gene families
	•	The accuracy of the species tree
	•	The quality of the gene trees or Phylogenic Hierachical OrthoGroups

The phylogenetic distance between extant species and any complete genome duplication events during their evolution are also critical factors.

I hope this helps,
best regards,
Alexandra

**Comment by jenny315** [comment]
Hi, Professor,
Thank you very much.
I appreciate your quick reply.
Jenny
