### ISSUE TITLE
Cannot assure my input format, especially the orthologyGroups.%s.list

### ISSUE THREAD

**Issue by MegadogDede** [DyogenIBENS/Agora#42]
Hi Agora team，
I have tried the script “src/agora-basic.py species-tree.nwk orthologyGroups/orthologyGroups.%s.list genes/genes.%s.list” with my own annotated genomes,but the log showed that "TypeError: list indices must be integers or slices, not str" .Is there something wrong with my input format?Having tried many times and check my input files,but still not clear with that. Your suggestion and guidance will be highly appreciated.
[log.txt](https://github.com/user-attachments/files/17830769/log.txt)

**Comment by alouis72** [comment]
Hi,

Thank you for using AGORA.
I hope I will be able to help you but I need more information about the process for that.
The log file you provided is the last step of Agora. 
Did all the previous steps run correctly?

What is the message of the output log of the entire pipeline? 

Are the 
ancGenes/ancGenes.log ok ?
pairwise/pairs-all/log ok ?
ancBlocks/denovo-all/log ok?
ancBlocks/denovo-all.scaffolds/ ok?


How did you generate the Orthologous groups?

regards,
Alex

**Comment by MegadogDede** [comment]
Thanks for your prompt response！
After checking my all kinds of log files,I have foud that there is something wrong with my N0 node.
First,the pairwise/pairs-all/log mentioned '0 conserved pairs between descendants N0...0 conserved pairs for N0',and then the ancBlocks/denovo-all/log mentioned that 'N0 empty list, no synthetic info on the distribution is available + 18006 singletons OK' then ancBlocks/denovo-all.scaffolds/log showed that 'Gene order comparison between N0 and  ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and  ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks
Gene order comparison between N0 and  ... None [None/None/None] [None/None/None] None [None/None-0] 0 adjacencies / 0 blocks'
I have upload my entire log you mentioned above,
.And my Orthologous groups are generated by orthofinder,and I also process them using the "convert_hogs_sp.py" 
Thanks for your help again!
with best regards
Wang

**Comment by alouis72** [comment]
Well, I guess you have a problem with FejMul, according to the pairs-all.log 

"Number of pairs for N0 [(**'FejMul', 0**), ('N1', 34943)]"
Are you sure that the gene names in FejMul are the same that in the Orthologous groups? 
Is FejMul assembled ? (If there is no intergenes in FejMul, Agora won't be able to infer ones in N0)

Hope this helps,
Alex

**Comment by MegadogDede** [comment]
Hi Alex,
Thank you from the bottom of my heart!Really appreciate your guidance and help!After checking my input you mentioned above,I have found that gene names in FejMul are not the same that in the Orthologous groups.Now I have sovle this problem.Sorry for my carelessness and interrupting.

With best regards,
Wang

**Comment by alouis72** [comment]
You're welcome.

best regards,
Alex
