### ISSUE TITLE
If the duplicate gene names caused the problem

### ISSUE THREAD

**Issue by MegadogDede** [DyogenIBENS/Agora#43]
Dear Alexandra,
When I ran agora-vertebrates.py, the ancGenes.log showed that 'Traceback (most recent call last):File "/public/xxx/Agora/Agora-master/src/ALL.reformatGeneFamilies.py", line 91, in <module>  raise AssertionError("Duplicated genes in the orthology group") 
  AssertionError: Duplicated genes in the orthology group' so I used 'sort orthologyGroups.<species>.list | uniq -d' to check and delete the duplicate gene names in my orthologous group file. After that I ran it again,the same problem occured. So I asked ChatGPT and add some debugging information in the  ALL.reformatGeneFamilies.py like 
'for og in orthologyGroups:
    n += 1
    if len(og) != len(set(og)):
        print(f"Duplicated genes in orthology group {n}: {og}", file=sys.stderr)
        raise AssertionError("Duplicated genes in the orthology group")'.
  After trying again, the ancGenes.log still showed the same as before, meanwhile output some possible ID in the log like'Updating the ancestral families of N0 ... adding names ... Duplicated genes in orthology group 9: ['Engystomops_pustulosus_rna-gnl|WGS_WNYA|PAC4GC_49059466_R1', 'Bufo_gargarizans_rna-XM_044272689.1_R0', 'Bombina_bombina_rna-XM_040438551.1_R0', 'Aquarana_catesbeiana_rna-gnl|WGS_LIAG|AB205_0145020A_mRNA_R4', 'Bufo_gargarizans_rna-XM_044299896.1_R2', 'Bombina_bombina_rna-XM_053713634.1_R4', 'Bufo_gargarizans_rna-XM_044299608.1_R0', ...]Traceback (most recent call last):
  File "/public2/xxx/Agora/Agora-master/src/ALL.reformatGeneFamilies.py", line 91, in <module> raise AssertionError("Duplicated genes in the orthology group")  AssertionError: Duplicated genes in the orthology group'.
But these ID are not the Duplicated genes because I have checked them. And I don't kown what's wrong with my input. Hopefully, you can assist me when you're available, and your suggestion and guidance will be highly appreciated.
thanks and regards
Wang

**Comment by alouis72** [comment]
Hi Wang,
would it be possible that you have same gene names in different species?
for example that 
rna-XM_044272689.1_R0 could be found in Bufo_gargarizans and in Bombina_bombina?

If so, the reformat won't be able to assign the good species to the gene. (and then, the AssertionError message has to be changed :-( )...

If no, you can send me the OrthologyGroup.N0.list (before reformat) file by email (alouis@bio.ens.psl.eu), and I will check it.

regards,
Alex

**Comment by MegadogDede** [comment]
Hi Alexandra,
Thanks for your prompt response! I think it's possible that the situation you described could be the cause. Because I annotated some of these species with the same or closely related species by Orthologous annotation. And I will check it！
Thanks for your guidance and help again!
Best wishes
Wang

**Comment by MegadogDede** [comment]
Hi Alex,
Thank you so much for your detailed and patient response! It is the problem that I had same gene names in different species that has caused that. With your help and guidance I have solved it and run the workflow fluently. And I truly appreciate your support and willingness to help me!( •͈ᴗ•͈)ᓂ- - -♡﻿
Once again, thank you, and I wish you all the best!
Best regards,
Wang

**Comment by alouis72** [comment]
Hi Wang,
thank you very much for the feed back.
I hope you will have nice results with AGORA.
best regards,
Alex
