### ISSUE TITLE
How to visualize Agora's results

### ISSUE THREAD

**Issue by ChenXi1201** [DyogenIBENS/Agora#5]
Hello, the species I want to study is not on Genomicus, so I used Agora to analyze, I want to know how to use the results of Agora to draw the picture like 'Karyotype View with ancestors' in Genomicus. Have you developed corresponding R  package or tools？Thanks
![image](https://user-images.githubusercontent.com/74816124/160540764-bd2a7ebe-d129-47ad-ad41-ba2bfade90f8.png)

**Comment by DyogenIBENS** [comment]
Hello,
thank you for using AGORA and Genomicus.
At the present time, we do not provide tool to generate such global view with command line. 
However, you can use src/misc.compareGenomes.py to generate the karyotypes one by one (with the option mode=drawKaryotype).

The first ancestral karyotype (one color per ancestral block) can be generate by comparing the genome to itself, eg:
src/misc.compareGenomes.py ancGenome.A1.list.bz2 ancGenome.A1.list.bz2  ancGenes.A1.list.bz2 -mode=drawKaryotype > A1.ps

The others, by comparing the genome (ancestral or modern) with the first ancestral one:
src/misc.compareGenomes.py genome.M1.list.bz2 ancGenome.A1.list.bz2  ancGenes.A1.list.bz2 -mode=drawKaryotype > M1.ps

etc...
options are available (+sortBySize, -minChrSize etc...) 

I hope this allows you to do what you want on your data,
Best wishes,
Alexandra

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦

**Comment by ChenXi1201** [comment]
> 
Thank you for your answer, but this script always reports this error. How can I solve it
![image](https://user-images.githubusercontent.com/74816124/166129635-a2da50fa-819c-44fd-9cfd-b865986c6f2b.png)

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦
