### ISSUE TITLE
-target==A1     this parameter seems to be unable to run

### ISSUE THREAD

**Issue by ChenXi1201** [DyogenIBENS/Agora#8]
I tested this parameter with example data
agora-generic.py Species.nwk orthologyGroups/orthologyGroups.%s.list.bz2 genes/genes.%s.list.bz2 -workingDir=A1 -target==A1
![image](https://user-images.githubusercontent.com/74816124/166175220-367902ed-9aa2-4acb-85b7-5f0118ee7ec6.png)

**Comment by DyogenIBENS** [comment]
Hi, 
you should try with only one "=" for the target parameter:
agora-generic.py Species.nwk orthologyGroups/orthologyGroups.%s.list.bz2 genes/genes.%s.list.bz2 -workingDir=A1 -target=A1

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦

**Comment by ChenXi1201** [comment]
Thanks
But I  want to reconstruct A1 only
 like that

![image](https://user-images.githubusercontent.com/74816124/166266038-373edae6-8d99-4703-b296-167b278784fb.png)
Is this function temporarily unavailable？

**Comment by DyogenIBENS** [comment]
Oh, I'm sorry for the mistaken answer, we'll come back to you as soon as the bug is corrected.
Sorry for that and thank you for pointing this out.

**Comment by muffato** [comment]
Hi @ChenXi1201 
I'm not able to reproduce the error you're reporting. This command-line (executed from an Agora checkout)
```
./src/agora-basic.py example/data/Species.nwk example/data/GeneTreeForest.nhx.bz2 example/data/genes/genes.%s.list.bz2 -target==A1 -workingDir=test6
```
only reconstructs the ancestor A1, and not its descendants – as opposite to `-target=A1` which reconstructs both A1 and A2.

Could you tell us more about your data-set ? e.g. share the species-tree and your command-line

**Comment by ChenXi1201** [comment]
Hello @muffato 
My command-line :
**agora-generic.py** Species.nwk orthologyGroups/orthologyGroups.%s.list.bz2 genes/genes.%s.list.bz2 -workingDir=A1 -target==A1.
The data I used is the data in your example.
It seems like agora-generic.py and agora-plants.py will reproduce this error.

**Comment by muffato** [comment]
Ah, right, gotcha ! I have temporarily fixed this on the `dev` branch

**Comment by ChenXi1201** [comment]
您的来信已收到，我会尽快查看，谢谢陈曦
